# Dependencies
# markdown:         redcarpet
# highlighter:      pygments

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title:            BBi
tagline:          'BurkinaBioinfo Platform'
description:      'Welcome to BBi, a cutting-edge platform for bioinformatics and computational biology.'
#baseurl: ""
url:              'burkinabioinfo.github.io'
author:
  name:           'Ezechiel B. TIBIRI'
  mail:            ezechiel.tibiri@ujkz.bf'


#paginate:         5

# Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/burkinabioinfo/burkinabioinfo.github.io

# Exclude specific pages and files from the site build
exclude:
  - course/*
